# Generated by Django 2.0.5 on 2018-06-06 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', '-modified', '-created']},
        ),
    ]
