# Generated by Django 2.0.5 on 2018-06-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180601_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', '-modified', '-created']},
        ),
        migrations.AlterModelOptions(
            name='eventattendee',
            options={'ordering': ['event__date', '-modified', '-created']},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
