# Generated by Django 2.0.5 on 2018-06-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('events', '0003_auto_20180607_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='attendee',
            name='role',
            field=models.CharField(choices=[('attendee', 'attendee'), ('doctor', 'doctor'), ('rep', 'rep')],
                                   default='attendee', max_length=55),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
