# Generated by Django 2.0.5 on 2018-06-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180603_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-modified', '-created']},
        ),
        migrations.AlterModelOptions(
            name='eventattendee',
            options={'ordering': ['-modified', '-created']},
        ),
    ]
